[package]
name = "auxmos"
version = "0.3.1"
authors = ["Putnam <putnam3145@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["auxcleanup_gas_deletion"]
auxcleanup_gas_deletion = ["auxcleanup"]
equalization = []
monstermos = ["equalization"]
putnamos = ["equalization"]
katmos = ["equalization"]
katmos_slow_decompression = ["katmos"]
reaction_hooks = []
plasma_fire_hook = ["reaction_hooks"]
trit_fire_hook = ["reaction_hooks"]
fusion_hook = ["reaction_hooks"]
generic_fire_hook = ["reaction_hooks"]
all_reaction_hooks = ["fusion_hook", "generic_fire_hook"]
all_reaction_hooks_old_fire = ["fusion_hook", "plasma_fire_hook", "trit_fire_hook"]
explosive_decompression = ["monstermos"]
putnamos_decompression = ["putnamos"]

[lib]
crate-type = ["cdylib"]

[dependencies]
auxtools = { git = "https://github.com/willox/auxtools"}
auxcallback = { git = "https://github.com/Putnam3145/auxcallback" }
auxcleanup = { git = "https://github.com/Putnam3145/auxcleanup", optional = true}
itertools = "0.10.3"
rayon = "1.5.2"
float-ord = "0.3.2"
crossbeam = "0.8.1"
flume = "0.10.12"
parking_lot = "0.12.0"
fxhash = "0.2.1"
nonmax = "0.5.0"
ahash = "0.7.6"
lazy_static = "1.4.0"
indexmap = { version = "1.8.1", features = ["rayon"] }
dashmap = { version = "5.2.0", features = ["rayon"] }

[dependencies.tinyvec]
version = "1.6.0"
features = ["rustc_1_57", "alloc"]

[profile.release]
lto = 'fat'
debug = true
panic = 'abort'
codegen-units = 1
opt-level = 3
